spring:
  messages:
    basename: label, utility-error, error
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      -
mongodb:
  empdb:
    uri: mongodb://digitaldot:digitaldot123@localhost:27017/empdb?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false

server:
  servlet:
    context-path: /