spring:
  messages:
    basename: label, utility-error, error
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      -
mongodb:
  ponto:
    uri: mongodb+srv://leo:123@pontodigital.3ysb3.mongodb.net/pontodigital?retryWrites=true&w=majority

server:
  servlet:
    context-path: /